# Generated by Django 3.0 on 2019-12-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='FlightStatus',
        ),
    ]
